### ISSUE TITLE
关于歌曲下载链接解析

### ISSUE THREAD

**Issue by SeanChao** [chenxuuu/24h-raspberry-live-on-bilibili#1]
你好！
我想根据您提供的PHP源码自己搭建下载链接解析服务，但是不知道何从入手，能否也提供一份简明教程？
不胜感激！

另：我在自己的直播间实验时，（使用您的下载链接解析），歌曲无法下载成功，对此感到困惑，能否提供可能导致下载失败的原因？

**Comment by chenxuuu** [comment]
哇这发得好正式啊。。。
搭建的话你bing搜搭建php服务器的教程就可以了，基本都有一键包的，不难
搭建完之后，把文件扔进去，再把网址换掉就可以了

歌曲无法下载成功的话，检查一下参数有没有该对，有没有读写文件的权限

**Comment by SeanChao** [comment]
我会进一步排查，非常感谢~

**Comment by chenxuuu** [comment]
问题解决了吗？
