### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by hanximeng** [chenxuuu/24h-raspberry-live-on-bilibili#10]
1.增加字幕滚动功能。
2.增加渲染控制功能，可选择是否进行渲染。
3.切歌时会鬼畜。
4.我点番剧后他会重复播放，一直放同一个视频。
5.支持网易歌单就最好了。

**Comment by chenxuuu** [comment]
**1正在研究，不是很好搞**
2我感觉没必要加，你可以自己写一下
3这个需要修改ffmpeg源码，程序也要用c来重写才能解决
4是特性，视频会扔到缓存目录
**5功能可以考虑**，但是歌单的话感觉万一歌曲太多的话，也不太好

**Comment by chenxuuu** [comment]
字幕滚动已加，虽然可能不是你想要的那种动画滚动吧，但是至少是滚动的233
网易歌单功能正在思考怎么加

**Comment by hanximeng** [comment]
多谢

**Comment by chenxuuu** [comment]
已添加翻译/原语言滚动歌词，效果应该还不错

**Comment by chenxuuu** [comment]
歌单点歌功能应该能用了，我还没测试，等我下班回家再测试
你可以先试试

**Comment by hanximeng** [comment]
麻烦了

**Comment by chenxuuu** [comment]
@hanximeng 歌单点播功能测试通过

**Comment by chenxuuu** [comment]
@all-contributors please add @hanximeng for idea
