### ISSUE TITLE
I met a few problems when I deployed it by your instructions.

### ISSUE THREAD

**Issue by luoyhang003** [chenxuuu/24h-raspberry-live-on-bilibili#12]
After I executed "python3 play.py", it says "Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtmp://txy.live-send.acg.tv/live-txy/streamname=live_11487603_2737999&key=xxxxxxxxxxx) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream."

Why this happened? And, what should I do to solve it?

By the way, it is really an awesome tool. Thanks a lot for your dedicate contributions.

**Comment by luoyhang003** [comment]
By the way, if you want, you can reply me by Chinese. I do not have a Chinese input, so I can only use English. Sorry about that.

**Comment by chenxuuu** [comment]
check "default_mp3" and "default_pic" folder,I think they are empty now🤣

If not ,please reply the model and system version.

**Comment by luoyhang003** [comment]
I have checked these two folder and make sure that they are not empty.

Device Information:
Raspberry pi 3
System Information:
Linux pi4luo 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

**Comment by luoyhang003** [comment]
I have posted whole the console output below:

no media
mp3 long:00:04:45
ffmpeg -re -loop 1 -r 3 -t 285 -f image2 -i "/home/pi/live/default_pic/ab.jpg" -i "/home/pi/live/default_mp3/Adele - Someone Like You.mp3" -vf ass="/home/pi/live/default.ass" -pix_fmt yuv420p -crf 24 -preset ultrafast -maxrate 3000k -acodec aac -b:a 192k -c:v h264_omx -f flv "rtmp://txy.live-send.acg.tv/live-txy/streamname=live_11487603_2737999&key=359819d08e7f4c353d51cebcc7db8efc"
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libass --enable-libfreetype --enable-omx --enable-omx-rpi --enable-encoder=h264_omx --enable-mmal --enable-hwaccel=h264_mmal --enable-decoder=h264_mmal
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, image2, from '/home/pi/live/default_pic/ab.jpg':
  Duration: 00:00:00.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1152x720 [SAR 72:72 DAR 8:5], 3 fps, 3 tbr, 3 tbn, 3 tbc
Input #1, mp3, from '/home/pi/live/default_mp3/Adele - Someone Like You.mp3':
  Metadata:
    encoder         : Lavf56.4.101
    album           : Someone Like You
    title           : Someone Like You
    comment         : 163 key(Don't modify):L64FU3W4YxX3ZFTmbZ+8/bBK+MZG/B8ITAl3LXs4r3E2VfEQUHBrJletO79HPCXxmUeZjHQGTIsv3+P9YwBdMORrRsttCB14izy/X4jTxnkSoK6o8PRibO0vceGuC5Bkiflg/7QieLeHSy6xwz1Ef8RJpcQnYVRV627/iuaykRiXicJCf4Fv9Pnz6hnJI4cW7MaJ7vLvYGxib/DFezbtYzHLlLZ9NboZteKm0Dlw1
    artist          : Adele
    track           : 1
  Duration: 00:04:45.36, start: 0.025056, bitrate: 321 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Stream #1:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 640x640 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Other
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtmp://txy.live-send.acg.tv/live-txy/streamname=live_11487603_2737999&key=359819d08e7f4c353d51cebcc7db8efc) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (rtmp://txy.live-send.acg.tv/live-txy/streamname=live_11487603_2737999&key=359819d08e7f4c353d51cebcc7db8efc) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (mp3 (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0x231caf0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[Parsed_ass_0 @ 0x2326fe0] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.2 (COMPLEX)
[Parsed_ass_0 @ 0x2326fe0] Using font provider fontconfig
[Parsed_ass_0 @ 0x2326fe0] Added subtitle file: '/home/pi/live/default.ass' (6 styles, 4 events)
[swscaler @ 0x245bcf0] deprecated pixel format used, make sure you did set range correctly
[Parsed_ass_0 @ 0x2326fe0] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/truetype/msttcorefonts/Arial.ttf, 0, ArialMT
[Parsed_ass_0 @ 0x2326fe0] Glyph 0x5F53 not found, selecting one more font for (微软雅黑, 400, 0)
[Parsed_ass_0 @ 0x2326fe0] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/truetype/wqy/wqy-zenhei.ttc, 0, WenQuanYiZenHei
[h264_omx @ 0x2327100] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://txy.live-send.acg.tv/live-txy/streamname=live_11487603_2737999&key=359819d08e7f4c353d51cebcc7db8efc':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1152x720 [SAR 1:1 DAR 8:5], q=2-31, 200 kb/s, 3 fps, 1k tbn, 3 tbc
    Metadata:
      encoder         : Lavc57.89.100 h264_omx
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc57.89.100 aac

**Comment by chenxuuu** [comment]
replace your key in your rtmp url。。。

try to delete ' -crf 24 'in play.py？

**Comment by luoyhang003** [comment]
Thanks a lot!
It worked after I deleted "-crf 24"

**Comment by ii404msn** [comment]
可以说明一下是什么原因吗？我也遇到了这个问题
