### ISSUE TITLE
编译并安装ffmpeg出现 gcc is unable to create an executable file. 的错误提示

### ISSUE THREAD

**Issue by eGluZl** [chenxuuu/24h-raspberry-live-on-bilibili#14]
系统：Ubuntu16.04 64位

按照本项目的readme文档中的编译命令（即：sudo ./configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libass --enable-libfreetype  --enable-omx --enable-omx-rpi --enable-encoder=h264_omx --enable-mmal --enable-hwaccel=h264_mmal --enable-decoder=h264_mmal）会出现如何下错误：

**gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.**

加上--enable-cross-compile的选项后则出现如下错误：

**gcc is unable to create an executable file.
C compiler test failed.**

**Comment by chenxuuu** [comment]
https://www.bing.com/search?FORM=INCOH2&PC=IFJ1&PTAG=ICO-c9d0fc87&q=gcc%20is%20unable%20to%20create%20an%20executable%20file.

**Comment by jdjingdian** [comment]
@XingyuHuo sudo ./configure --arch=x86_64 --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libass --enable-libfreetype --enable-encoder=h264_qsv --enable-hwaccel=h264_qsv --enable-decoder=h264_qsv ,我记得我的是这样的，我的设备是CentOS的VPS，然后要安装最新版的nasm和yasm哦

**Comment by chenxuuu** [comment]
vps的话，直接`sudo apt-get install ffmpeg`就好了啊
