### ISSUE TITLE
大佬能不能设置停止播放当前歌单

### ISSUE THREAD

**Issue by XuewanZhao** [chenxuuu/24h-raspberry-live-on-bilibili#15]
就像我昨天点播了我的歌单 但是太晚了要休息了 就想关直播的时候把自己的歌单关了 不影响后面的观众点播，但是没有这个选项。比如我刚刚又去直播间，上个点播的人已经走了（直播间没人）但是他还有七十多首没播完QUQ。求增加功能！
B站id赵校长

**Comment by chenxuuu** [comment]
现在按歌单播放的功能是没有把一整个歌单的歌当作整体考虑的，是一首一首分开独立的，所有这个功能暂时没法实现
等我有空闲再加新功能吧，不过加之前要重构。。

**Comment by XuewanZhao** [comment]
em 也许可以试试 
输入“停止播放当前歌单”->抓取用户id->匹配播放列表里的点播用户名->删除（切过）匹配到的歌曲
没有仔细看完大佬的代码...但是感觉使用的时候应该树莓派里存的有这些信息...如果和实际出入很大的话请无视.... ：P

**Comment by jdjingdian** [comment]
@XuewanZhao 我自己是加了一段清空列表直接把全部点歌都清空掉……特定用户使用，我个人的改进思路是可以读取info文件里面的信息然后把指定点歌人点的歌删掉，emmmmm不知道能不能帮上忙
`def del_ept():

        send_dm_long('已收到管理员爸爸的指令，正在清空')
        paths = path+'/downloads'   #获取目录下所有文件
        for i in os.listdir(paths):
            paths_file = os.path.join(paths,i)
            
            if os.path.isfile(paths_file):
                os.remove(paths_file)
            else:
                for k in os.listdir(paths_file):  
                    paths_file2 =os.path.join(paths_file,k)
                    if os.path.isfile(paths_file2):
                        os.remove(paths_file2)
        os.system('killall ffmpeg')
        send_dm_long('已经清空列表啦~~么么艹')`

然后在下面

`elif ((s == '清空列表') and (user=='Jarvis-Ultron') | (user=='JU的投食员')):
        del_ept()`

**Comment by XuewanZhao** [comment]
@jdjingdian 对对，我想的大概也是这样，赞

**Comment by chenxuuu** [comment]
@all-contributors please add @XuewanZhao for idea
