### ISSUE TITLE
关于卡顿

### ISSUE THREAD

**Issue by lamzero** [chenxuuu/24h-raspberry-live-on-bilibili#2]
您好，感谢您开发这个项目，我在用的时候发现经常卡顿，但是看了下cpu使用率，并没有满载，请问有解决办法吗？

**Comment by chenxuuu** [comment]
你用的是2b还是3b啊？我代码里加入了硬解码的参数了，好像2b运行有些吃力，可以试试改成软解，代码翻翻commit记录应该是有的
我之前用2b开直播的时候也是很卡，当时是渲染完毕再推流的
现在这个脚本是一边渲染一边推流，渲染速度慢的话会卡顿

另外注意图片尽量用1280x720分辨率的

**Comment by lamzero** [comment]
我是树莓派3b，图片大了确实是会卡，用720P的图片除了换歌以外都挺流畅的，已经满足直播了。我的问题可能之前没描述清楚，在播放mv的时候会卡，ffmpeg的速率一般0.64，无论用libx264还是h264_omx都卡，-r 8也卡，mv还是个480p的，看io也没用多少，cpu总是不能全力工作。

**Comment by chenxuuu** [comment]
视频推流卡顿的问题我近期回去尝试解决，你可以先watch这个项目，或者你写好pr也行

**Comment by chenxuuu** [comment]
已更新视频推流逻辑，你试一试还卡不卡？

**Comment by lamzero** [comment]
好的，我马上试一下

**Comment by lamzero** [comment]
这个新版似乎有问题，av和mv都播放不了，下载都没问题，一到转码，就出错了。

**Comment by lamzero** [comment]
对于B站的视频，可以考虑直接用copy推，用户上传的视频，b站应该进行过转码

**Comment by chenxuuu** [comment]
不行，加ass字幕的话不能用copy
现在的测试代码就是先提前转码，再用c:v copy,c:a copy参数推流的
你如果有空的话可以帮我检查下，修好了pr就行
我晚上才有空修

**Comment by chenxuuu** [comment]
小改了一下，我现在没法测试，你可以帮我测试一下
测试结果请回复一下，谢谢

**Comment by lamzero** [comment]
好的

**Comment by lamzero** [comment]
刚刚的问题没有了，视频进入渲染中，不过当前播放的视频有点卡，我准备加个限制线程数的参数。

**Comment by lamzero** [comment]
我在ffmpeg后面加了个-threads 1，情况好了些。

**Comment by lamzero** [comment]
ok，不卡了，我发现貌似树莓派的性能每秒也就能渲染4帧图像，等下改为2试试。

**Comment by lamzero** [comment]
我发现字幕那里/downloads/两边的引号似乎错了，没有把ass字幕加上，我改为 '  了，才出现字幕。

**Comment by chenxuuu** [comment]
没有错啊？
