### ISSUE TITLE
自动显示媒体文件长度和当前播放进度是有可能做到的吗？

### ISSUE THREAD

**Issue by a08381** [chenxuuu/24h-raspberry-live-on-bilibili#21]
能做到滚动歌词的话，显示媒体文件长度和当前播放进度应该也是没问题的？

**Comment by a08381** [comment]
`    def get_file_times(self,filename):  
        u""" 
        获取视频时长（s:秒） 
        """  
        clip = VideoFileClip(filename)  
        file_time = self.timeConvert(clip.duration)  
        return file_time`

我找到了这么一段代码，理论上获取到视频长度之后直接按秒遍历添加Dialogue就可以了吧

**Comment by chenxuuu** [comment]
@a08381 可以做到，按你楼上的代码理论上是可以的，就是加个ass字幕而已
改好了欢迎pr

**Comment by chenxuuu** [comment]
![qq 20180406191337](https://user-images.githubusercontent.com/10357394/38418359-aa8402dc-39ce-11e8-87c6-6bc06c6815fb.png)
搞好咯

**Comment by chenxuuu** [comment]
@all-contributors please add @a08381 for idea
