### ISSUE TITLE
开始运行后提示'Unknown encoder 'h264_omx'请教下怎么解决

### ISSUE THREAD

**Issue by BakaNoble** [chenxuuu/24h-raspberry-live-on-bilibili#22]
[mp3 @ 0x2be4c40] Estimating duration from bitrate, this may be inaccurate
Input #1, mp3, from '/root/live/default_mp3/bx.mp3':
  Metadata:
    title           : Teddy      
    album           : TVアニメ「神様のメモ帳」オリジナルサウンドトラック
    album_artist    : 岩崎琢
    artist          : 岩崎琢
  Duration: 00:04:10.44, start: 0.000000, bitrate: 146 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
    Stream #1:1: Video: png, rgb24(pc), 640x640, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
Unknown encoder 'h264_omx'
no media
mp3 long:00:04:10

**Comment by BakaNoble** [comment]
在ubuntu下运行的

**Comment by chenxuuu** [comment]
重新按教程编译ffmpeg

**Comment by chenxuuu** [comment]
或者把代码里的h264_omx参数换成x264，即可
