### ISSUE TITLE
直播失败，全部按照按照步骤做

### ISSUE THREAD

**Issue by zeruns** [chenxuuu/24h-raspberry-live-on-bilibili#25]
![1](https://user-images.githubusercontent.com/10357394/35427411-3685a9be-02a4-11e8-8a8d-8930d6951a17.png)
![2](https://user-images.githubusercontent.com/10357394/35427413-3c34aee6-02a4-11e8-9212-e57532d54e51.png)
![3](https://user-images.githubusercontent.com/10357394/35427418-3e420a44-02a4-11e8-9a4a-21daabe830ce.png)

**Comment by chenxuuu** [comment]
编译ffmpeg的时候参数不对吧？要么就是系统版本不是官方版，导致硬解码的文件都不存在
你试试官方系统镜像
