### ISSUE TITLE
脚本的后台运行应该换个方式

### ISSUE THREAD

**Issue by Droid-MAX** [chenxuuu/24h-raspberry-live-on-bilibili#31]
可以写个shell脚本来管理，可以参照一下我的agentx1项目里的管理脚本
[agentx1](https://github.com/Droid-MAX/agentx1/blob/61d3930057c8067e35e89d2df22a57140e37cedd/root/etc/init.d/agentx1)

我这个是用在openwrt软件包里的，不过适当修改一下应该可以用在树莓派上

**Comment by chenxuuu** [comment]
这东西应该让他们自己解决
