### ISSUE TITLE
尝试点播bilibili视频报“出错了：请检查命令或重试”错误

### ISSUE THREAD

**Issue by ssnh** [chenxuuu/24h-raspberry-live-on-bilibili#33]
如题，直播间用av+id点播主站视频全部报“出错了：请检查命令或重试”，you-get版本是
you-get: version 0.4.1060, a tiny downloader that scrapes the web.
按照代码注释没有启用瓜子投喂点歌，除了B站点播出错以外其他功能正常。求大佬支招，谢谢~
系统用Linux Deploy搭建的Debian 9 ffmpeg version N-90065-g8a8d0b319a Python 3.5.3

**Comment by chenxuuu** [comment]
where's the error message in bash?

**Comment by ssnh** [comment]
感谢大佬回复~
```
0 说: av20626365
19
[log]发送弹幕：已收到0的指令
1 说: 已收到0的指令
[log]downloading bilibili video:https://www.bilibili.com/video/av20626365
[log]发送弹幕：出错了：请检查命令或重试
1 说: 出错了：请检查命令或重试
0 说: av1714157
19
[log]发送弹幕：已收到0的指令
1 说: 已收到0的指令
[log]downloading bilibili video:https://www.bilibili.com/video/av1714157
[log]发送弹幕：出错了：请检查命令或重试
1 说: 出错了：请检查命令或重试
0 说: av9179876
19
[log]发送弹幕：已收到0的指令
1 说: 已收到0的指令
[log]downloading bilibili video:https://www.bilibili.com/video/av9179876
[log]发送弹幕：出错了：请检查命令或重试
1 说: 出错了：请检查命令或重试
```
`
(昵称换成了数字，其他没有变化)

**Comment by chenxuuu** [comment]
`postdm.py`的第`231`行改一下，大概改成：

```python
        send_dm_long('视频'+video_title+'渲染完毕，已加入播放队列')
     except Exception as e: #报错提示，一般只会出现在获取标题失败时出现，就是点播参数不对
        send_dm_long('出错了：请检查命令或重试')
        print(e)
        if var_set.use_gift_check:
            give_coin(user,500)
```
然后看报错信息再发来

**Comment by ssnh** [comment]
[log]发送弹幕：已收到xx的指令
bb 说: 已收到xx的指令
[log]downloading bilibili video:https://www.bilibili.com/video/av10246
[log]发送弹幕：出错了：请检查命令或重试
bb 说: 出错了：请检查命令或重试
Expecting value: line 1 column 1 (char 0)
xx 说: av22203271
19
[log]发送弹幕：已收到xx的指令
bb 说: 已收到xx的指令
[log]downloading bilibili video:https://www.bilibili.com/video/av22203271
[log]发送弹幕：出错了：请检查命令或重试
bb 说: 出错了：请检查命令或重试
Expecting value: line 1 column 1 (char 0)

**Comment by chenxuuu** [comment]
203后面加上
```
print(video_info)
```
再看结果

**Comment by ssnh** [comment]
加完之后和刚才发的log一样。。。

**Comment by chenxuuu** [comment]
重装ffmpeg为稳定版

**Comment by ssnh** [comment]
屏蔽了you-get警告的那两行代码后整个世界都太平了。。。虽然还是重新编译ffmpeg更靠谱点
