### ISSUE TITLE
大佬，搭建完成始终是这个情况怎么办啊？

### ISSUE THREAD

**Issue by 5wszxt** [chenxuuu/24h-raspberry-live-on-bilibili#36]
皆因惰性 说: id4071236
10
[log]发送弹幕：已收到皆因惰性的指令
欧皮酱 说: 已收到皆因惰性的指令
[log]发送弹幕：正在下载id4071236
欧皮酱 说: 正在下载id4071236
[log]getting url:id4071236
no files found!
/home/pi/24h-raspberry-live-on-bilibili/downloads/1526176972.0
[log]发送弹幕：id4071236下载完成，已加入播放队
欧皮酱 说: id4071236下载完成，已加入播放队
10
[log]发送弹幕：列
[log]已添加排队项目：id4071236
[log]发送弹幕：已收到欧皮酱的指令
欧皮酱 说: 列
欧皮酱 说: 已收到欧皮酱的指令
[log]发送弹幕：正在下载id4071236下载完成，已加
欧皮酱 说: 正在下载id4071236下载完成，已加
[log]发送弹幕：入播放队
欧皮酱 说: 入播放队
[log]getting url:id4071236下载完成，已加入播放队
[log]发送弹幕：出错了：请检查命令或重试
欧皮酱 说: 出错了：请检查命令或重试
[log]下载文件出错：id4071236下载完成，已加入播放队,url:
delete/home/pi/24h-raspberry-live-on-bilibili/downloads/1526176990.0.mp3
delete error
delete/home/pi/24h-raspberry-live-on-bilibili/downloads/1526176990.0.mp4
delete error
delete/home/pi/24h-raspberry-live-on-bilibili/downloads/1526176990.0.flv
delete error

**Comment by shinBZ** [comment]
我也有这种情况，不过我没管他，也能正常运行

**Comment by 5wszxt** [comment]
不行的我，上面提示找不到文件，然后下面又是删除失败，b站那个直接点播没反应，虽然这个终端会有命令提示。。。

**Comment by shinBZ** [comment]
不知道。虽然我也不能直接点播B站视频，但是mv是正常的，我报删除错误但是不影响正常使用

**Comment by 5wszxt** [comment]
又搞了一次，还是不行，都连自带的音频和图片不显示，执行第一条启动代码就看到疯狂的刷资源地址和提示
sh:1:ffmpeg:not found

**Comment by 5wszxt** [comment]
@chenxuuu 大佬有没有解决办法？（手动滑稽）
