### ISSUE TITLE
关于cookie

### ISSUE THREAD

**Issue by polychromate** [chenxuuu/24h-raspberry-live-on-bilibili#37]
![soxn0 6i_d23h sjsy 2u w](https://user-images.githubusercontent.com/22171674/40001595-21bec9f8-57c1-11e8-90d7-ed9a211217e7.png)

发送消息后在network选项卡里面，send项目中的cookie里，未找到request head项，这是Firefox的。Chrome游览器里面有request head项，但是value为空的。
csrf_token项，两个游览器都没找到。

![wfbes933zyk7 p lgw eyo](https://user-images.githubusercontent.com/22171674/40002059-2ca19a16-57c2-11e8-8c58-16caacc3129e.png)

然后那两个没填，直接运行，得到了这样一个报错，请问是什么情况。

谢谢帮助。

**Comment by chenxuuu** [comment]
1. 复制的是全体cookie，而不是某一项

2. 下面的命令执行过了吗？
```python
sudo pip3 install moviepy
```

**Comment by polychromate** [comment]
1.能否截个图，不是很理解
2.执行了

**Comment by shinBZ** [comment]
我用QQ浏览器，都有

**Comment by chenxuuu** [comment]
1. 
![image](https://user-images.githubusercontent.com/10357394/40029358-d1c0ebce-5816-11e8-98d5-0f8d2688c4d3.png)

2. 你肯定没装上这东西，看不懂英语报错说的什么吗？要不你试试在python3命令行里`import moviepy`？你看看会显示什么？
