### ISSUE TITLE
运行play.py时出错

### ISSUE THREAD

**Issue by SoukinOKATU** [chenxuuu/24h-raspberry-live-on-bilibili#4]
ffmpeg version N-89230-g279d2599dd Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      56.  2.100 / 56.  2.100
  libavcodec     58.  3.105 / 58.  3.105
  libavformat    58.  2.102 / 58.  2.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  3.100 /  7.  3.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[mjpeg @ 0x2f987c0] No JPEG data found in image
[mjpeg @ 0x2f987c0] Single field
Input #0, image2, from '/home/pi/24h-raspberry-live-on-bilibili/default_pic/aa.jpg':
  Duration: 00:00:00.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 960x960 [SAR 96:96 DAR 1:1], 3 fps, 3 tbr, 3 tbn, 3 tbc
Input #1, mp3, from '/home/pi/24h-raspberry-live-on-bilibili/default_mp3/aa.mp3':
  Metadata:
    encoder         : Lavf57.25.100
    disc            : 3
    track           : 32
    artist          : Lyn
  Duration: 00:01:34.85, start: 0.025056, bitrate: 338 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : Lavc57.24
    Stream #1:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 640x640 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Media (e.g. label side of CD)
Unknown encoder 'h264_omx'

出现No JPEG data found in image和Unknown encoder 'h264_omx'` 怎么解决

**Comment by chenxuuu** [comment]
请按照教程，重新编译ffmpeg
只需要按编译ffmpeg这一部分重做就行了

**Comment by chenxuuu** [comment]
我说的教程是github项目readme里的，这个教程是一直在更新的

**Comment by SoukinOKATU** [comment]
那么搭建的点歌api的php服务的网址需要外网映射么，还是可以直接用内网ip？

**Comment by chenxuuu** [comment]
树莓派能连上，能打开，就行
不需要映射到外网

**Comment by SoukinOKATU** [comment]
用apache搭建php后，把文件放在www/163文件夹下，访问192.168.1.XXX/163 也确实出现了nothing的输出，但弹幕点播后，开始下载音乐时候就出现500错误，怎么回事？

**Comment by SoukinOKATU** [comment]
算了，自行解决了，没装php curl。。。。囧
