### ISSUE TITLE
ffmpeg已经不能编译通过;点歌列表失效;弹幕无歌词

### ISSUE THREAD

**Issue by cmt2001** [chenxuuu/24h-raspberry-live-on-bilibili#40]
1.readme给的ffmpeg版本太低，编译不通过，换成3.4.2
2.点歌，弹幕反馈点歌成功，字幕无显示，可以正常下载，但点歌列表查询时显示列表歌曲0首
3.弹幕并不会刷新歌词，只会在每次播完一首歌刷新

**Comment by chenxuuu** [comment]
1.高版本的ffmpeg没有硬解码，会卡的你不要不要的，当然你要是用vps而不是用树莓派的话，当我没说
2.没有视频显示反馈的功能，只有弹幕功能，并且请确认给予了脚本足够的权限并且路径设置正确
3.没看懂
