### ISSUE TITLE
编译 x264 出错.../尝试移植至非树莓派

### ISSUE THREAD

**Issue by VergeDX** [chenxuuu/24h-raspberry-live-on-bilibili#41]
在 configure 时：./configure --enable-static --disable-opencl
请问该如何解决呢？

/usr/bin/x86_64-linux-gnu-ld: 最后的链结失败: 输出不可表示的节
collect2: error: ld returned 1 exit status
Makefile:263: recipe for target 'x264' failed
make: *** [x264] Error 1
vanilla@vanilla-Presario-V3700-Notebook-PC:~/git/x264$

**Comment by VergeDX** [comment]
问题已解决
顺便   请问本程序可以在非树莓派 Ubuntu 设备上跑吗？

**Comment by chenxuuu** [comment]
@VergeDX 可以跑，把所有硬解码相关的东西换成x264软解吗就行了
我最早就是在腾讯云上面跑的，等有时间改一个vps版
vps主要是上行带宽太小了，码率限制需要变态一点。。

**Comment by VergeDX** [comment]
唔   我现在是一直报错：Unknown encoder 'h264_omx'

sudo ./configure --help | grep h264 看到有 
 --enable-libopenh264     enable H.264 encoding via OpenH264 [no]

然后 sudo ./configure --enable-gpl --enable-libx264 --enable-nonfree  --enable-libass --enable-libopenh264 --enable-libfreetype
请问使用的软解码全了吗？

谢谢w

**Comment by chenxuuu** [comment]
omx就是硬解码

**Comment by chenxuuu** [comment]
py脚本里的命令要改的，解码器改掉

**Comment by VergeDX** [comment]
好的   感谢回复

**Comment by chenxuuu** [comment]
py脚本里的命令要改的，解码器改掉

**Comment by VergeDX** [comment]
窝把 play.py 中的所有（8 处）h264_omx 都改为了 h264

出现了这样的报错：
[AVFilterGraph @ 0x556ba7146b60] No such filter: 'ass'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[image2 @ 0x556ba7110b40] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Conversion failed!
no media

**Comment by chenxuuu** [comment]
不要直接apt安装，要源码安装
默认不带ass的，我编译参数里有ass

**Comment by VergeDX** [comment]
直接找了一个比较全的二进制文件用了_(:з」∠)_
然后用 h264 解码器跑您的库和那个重构的库
各种无限循环   也不报错
可能是我配置太辣鸡了.jpg

**Comment by VergeDX** [comment]
~~有生之年等您出个VPS版~~
