### ISSUE TITLE
点播视频之后没法播放 在终端有报错提示geturl之后格式错误 接着ffmpeg提示文件损坏

### ISSUE THREAD

**Issue by jidesheng6** [chenxuuu/24h-raspberry-live-on-bilibili#42]
提示信息如下【请问大佬是什么原因呀】：

> [log]getting url:mv5455140
> /userapp/bz/downloads/1534742025.0.mp4
> shit
> [Errno 8] Exec format error
> [log]发送弹幕：mv5455140下载完成，等待渲染
> 我砍人很疼 说: mv5455140下载完成，等待渲染
> [error]弹幕发送失败：mv5455140正在渲染
> {'code': 0, 'data': [], 'msg': 'msg in 1s'}
> ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
>   configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libass --enable-libfreetype --enable-omx --enable-omx-rpi --enable-encoder=h264_omx --enable-mmal --enable-hwaccel=h264_mmal --enable-decoder=h264_mmal
>   libavutil      56. 14.100 / 56. 14.100
>   libavcodec     58. 18.100 / 58. 18.100
>   libavformat    58. 12.100 / 58. 12.100
>   libavdevice    58.  3.100 / 58.  3.100
>   libavfilter     7. 16.100 /  7. 16.100
>   libswscale      5.  1.100 /  5.  1.100
>   libswresample   3.  1.100 /  3.  1.100
>   libpostproc    55.  1.100 / 55.  1.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/userapp/bz/downloads/1534742025.0.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf56.40.101
>   Duration: 00:04:05.83, start: 0.000000, bitrate: 852 kb/s
>     Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1:1 DAR 427:240], 712 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>     Stream #0:1(zho): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 134 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
>   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
> Press [q] to stop, [?] for help
> [Parsed_ass_1 @ 0x1c9a8f0] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.2 (COMPLEX)
> [Parsed_ass_1 @ 0x1c9a8f0] Using font provider fontconfig
> [Parsed_ass_1 @ 0x1c9a8f0] Added subtitle file: '/userapp/bz/downloads/1534742025.0ok.ass' (10 styles, 16 events)
> [Parsed_ass_1 @ 0x1c9a8f0] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/truetype/msttcorefonts/Arial.ttf, 0, ArialMT
> [Parsed_ass_1 @ 0x1c9a8f0] Glyph 0x5F53 not found, selecting one more font for (微软雅黑, 400, 0)
> [Parsed_ass_1 @ 0x1c9a8f0] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/truetype/wqy/wqy-zenhei.ttc, 0, WenQuanYiZenHei
> [libx264 @ 0x183cac0] VBV maxrate specified, but no bufsize, ignored
> [libx264 @ 0x183cac0] using SAR=1/1
> [libx264 @ 0x183cac0] using cpu capabilities: ARMv6 NEON
> [libx264 @ 0x183cac0] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
> *** Error in `ffmpeg': corrupted size vs. prev_size: 0x022def18 ***
> Aborted
> delete/userapp/bz/downloads/1534742025.0.mp4
>

**Comment by chenxuuu** [comment]
方便再用新版测试下吗？

**Comment by jidesheng6** [comment]
抱歉，，，，之前不会用github，我现在才看到。。。。。

**Comment by jidesheng6** [comment]
> 抱歉，，，，之前不会用github，我现在才看到。。。。。



> 方便再用新版测试下吗？

抱歉，，，，之前不会用github，我现在才看到。。。。。

**Comment by jidesheng6** [comment]
> 方便再用新版测试下吗？

抱歉，，，，之前不会用github，我现在才看到。。。。。
