### ISSUE TITLE
更新最新版后点歌报can't sync to MPEG frame

### ISSUE THREAD

**Issue by ssnh** [chenxuuu/24h-raspberry-live-on-bilibili#46]
如题,更新最新版后点歌后台报can't sync to MPEG frame,结果就是点歌失败,只能播放更新前剩余的歌曲 ...求大佬支招
![2018-12-03_183313.jpg](https://i.loli.net/2018/12/03/5c0506bd567d6.jpg)

**Comment by chenxuuu** [comment]
重新按readme部署一遍ffmpeg吧，之前用的是ffmpeg3.3.2，现在用ffmpeg4.0了

**Comment by ssnh** [comment]
感谢大佬回复,我试着编一遍试试看

**Comment by ssnh** [comment]
ffmpeg和x264全重新编了一遍,看起来并没什么用...ffmpeg升级到4.1,x264按教程安装的...

**Comment by chenxuuu** [comment]
歌曲id报一下，我估计这个歌的文件格式不是MP3，应该是m4a之类的格式
导致`ass_maker.py`的69行的代码报错
```python
audio = MP3(path+'/downloads/'+str(filename)+'.mp3')
```

**Comment by ssnh** [comment]
id=206276 我发现下载的mp3 文件不足1K,修改后缀用记事本打开是这样的
{"code":-460,"msg":"Cheating"}
有趣的是用本地搭建的php解析却能获得mp3下载链接...

**Comment by chenxuuu** [comment]
感觉不该啊，下载歌曲的目标网址是这个：
```
http://music.163.com/song/media/outer/url?id=206276
```

**Comment by chenxuuu** [comment]
ok
我知道原因了

**Comment by ssnh** [comment]
嗯,确实可以用了.赞美大佬!
