### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by kmzs123** [chenxuuu/24h-raspberry-live-on-bilibili#48]
环境都按照readme进行了安装，运行了却在下载3.3.1版本的ffmpeg

下载完成之后就不会再有问题

以下运行记录

----------

pi@pi:~ $ cd 24h*

pi@pi:~/24h-raspberry-live-on-bilibili $ python3 play.py

Imageio: 'ffmpeg-linux32-v3.3.1' was not found on your computer; downloading it now.

Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux32-v3.3.1 (32.8 MB)

Downloading: 393216/34368176 bytes (1.1%)

----------

另外，对于B站的多P视频好像会下载失败。在下载多P的B站链接时 you-get 会提示增加某个参数进行下载整个列表。

**Comment by chenxuuu** [comment]
只会下载一次，python库的锅我不背
点播视频功能暂时不再维护

**Comment by kmzs123** [comment]
那我能不能在准备环境的时候跳过ffmpeg的编译 @chenxuuu
