### ISSUE TITLE
用户点歌后直播间无弹幕提示

### ISSUE THREAD

**Issue by ssnh** [chenxuuu/24h-raspberry-live-on-bilibili#49]
**描述bug**
简洁地写一下bug的内容
用户点歌后直播间无弹幕提示,后台提示[error]send dm error.(已经更新用户cookie)
**复现步骤**
按如下步骤可以复现bug：
1. 打开直播间
2. 发送歌曲ID号码
3. 点歌成功但没有弹幕反馈提示.

**本应出现的正常状态**
点歌成功应有弹幕反馈提示.

**截屏或log记录**

**环境信息**
 - 系统详细版本：[Debian GNU/Linux 9 (stretch)]
 - 硬件信息： [running via Linux Deploy]
ffmpeg version 4.1 x264 core:157 r2935 545de2f 

**其他说明**
另外我曾经遇到过这个报错提示
File "/usr/lib/python3.5/asyncio/selector events.py", line 723, in _read_ready data = self._sock.recv(self.max_size) TimeoutError: [Errno 110] Connection timed out
我这里只能强行重启系统才能解决这个"Connection timed out"问题

**Comment by chenxuuu** [comment]
已更正，感谢反馈
