### ISSUE TITLE
下载id XXXX完成，正在加入队列 该语句发送弹幕有问题

### ISSUE THREAD

**Issue by SoukinOKATU** [chenxuuu/24h-raspberry-live-on-bilibili#5]
其中的id xxxxxx会被python获取，作为新的指令推送到api下载，
具体表现为
点歌人：id XXXXXXXX
直播人 : 已收到点歌人的指令
直播人 : 正在下载id XXXXXXXX
直播人 : **id XXXXXXXX完成**
直播人 : 已收到**直播人**的指令
直播人 : 正在下载**id xxxxxx 完成**
直播人 : 出错了：下载出错，请换一首或重试

id xxxxxx 完成 这句话会被系统当作指令。

然后虽然能够正常下载前一个用户点的歌曲，但是还是会报错一次。

**Comment by chenxuuu** [comment]
请修改`post_dm.py`文件的第191行

**Comment by SoukinOKATU** [comment]
send_dm('已收到'+user+'的指令')
这个修改成什么样？

**Comment by chenxuuu** [comment]
`post_dm.py`文件的`if(user == '接待喵'): #防止自循环`
改为你的机器人的名字
