### ISSUE TITLE
"Fatal read error on socket transport"报错后bilibiliClient.py未能重新启动

### ISSUE THREAD

**Issue by ssnh** [chenxuuu/24h-raspberry-live-on-bilibili#50]
**描述bug**
我这里用supervisor代替screen启动程序.然后今天看到点歌程序挂掉后没能自己重新启动.

**复现步骤**
按如下步骤可以复现bug：
大概是网络IP短时间变动能够触发

**本应出现的正常状态**
bilibiliClient.py报错后应该自动重启

**截屏或log记录**
Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0xb4fbb0d0>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out

**环境信息**

**其他说明**
大佬有可能改进吗,就是能够做到报上述错误还能重新启动bilibiliClient.py

**Comment by chenxuuu** [comment]
文件最后几行已经有崩溃自动重启功能

**Comment by ssnh** [comment]
大佬如果有空你可以试试重现下就能明白了233 可能我这里网络有点渣吧...
