### ISSUE TITLE
关于直播字幕问题

### ISSUE THREAD

**Issue by luojiaquan7737** [chenxuuu/24h-raspberry-live-on-bilibili#6]
通过不断努力前面全部弄好了。就查目前那个直播字幕不能显示.还请麻烦写上去，行吗？🙏🙏

**Comment by chenxuuu** [comment]
代码是git上面最新的代码吗？

**Comment by luojiaquan7737** [comment]
感谢回复，代码是最新的。但是我朋友重新装系统是可以显示。我先重装系统试试能不能解决！

**Comment by luojiaquan7737** [comment]
还是一样没解决，系统是今年七月份的，唯独字幕不能显示，其他正常

**Comment by chenxuuu** [comment]
ffmpeg日志显示的什么？是不是没安装字体？

**Comment by luojiaquan7737** [comment]
关于ffmpeg日志我不知如何查看，字体是安装成功的

**Comment by chenxuuu** [comment]
`screen -ls`
查看screen id
`screen -r 你play.py所在screen的id`
在切歌播放mp3文件的时候，把所有ffmpeg日志粘贴在这里

**Comment by luojiaquan7737** [comment]
`
pi@raspberrypi:~/live $ screen -r 1453
[log][2017-11-29 23:20:15]斜月三星洞博客-洞主:已加入播
[log]getting url:id463746226下载完成，已加入播
[log]发送弹幕：出错了：下载出错，请换一首或重试
[log][2017-11-29 23:20:17]斜月三星洞博客-洞主:出错了：下载出错，请换一首或重试
[log]下载文件出错：id463746226下载完成，已加入播,url:
delete error
delete error
delete error
[log][2017-11-29 23:20:26]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到1次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:27]斜月三星洞博客-洞主:已收到1次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:32]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到2次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:32]斜月三星洞博客-洞主:已收到2次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:38]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到3次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:39]斜月三星洞博客-洞主:已收到3次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:44]斜月三星洞博客-洞主:切歌
[error]弹幕发送失败：已收到4次切歌请求，达到五次将切歌
{'code': 0, 'data': [], 'msg': 'msg in 1s'}
[log][2017-11-29 23:20:54]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已执行切歌动作
[log][2017-11-29 23:20:55]斜月三星洞博客-洞主:已执行切歌动作
`
日志如上

**Comment by luojiaquan7737** [comment]
`
pi@raspberrypi:~/live $ screen -r 1453
[log][2017-11-29 23:20:15]斜月三星洞博客-洞主:已加入播
[log]getting url:id463746226下载完成，已加入播
[log]发送弹幕：出错了：下载出错，请换一首或重试
[log][2017-11-29 23:20:17]斜月三星洞博客-洞主:出错了：下载出错，请换一首或重试
[log]下载文件出错：id463746226下载完成，已加入播,url:
delete error
delete error
delete error
[log][2017-11-29 23:20:26]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到1次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:27]斜月三星洞博客-洞主:已收到1次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:32]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到2次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:32]斜月三星洞博客-洞主:已收到2次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:38]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已收到3次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:39]斜月三星洞博客-洞主:已收到3次切歌请求，达到五次将切歌
[log][2017-11-29 23:20:44]斜月三星洞博客-洞主:切歌
[error]弹幕发送失败：已收到4次切歌请求，达到五次将切歌
{'code': 0, 'data': [], 'msg': 'msg in 1s'}
[log][2017-11-29 23:20:54]斜月三星洞博客-洞主:切歌
[log]发送弹幕：已执行切歌动作
[log][2017-11-29 23:20:55]斜月三星洞博客-洞主:已执行切歌动作
`
日志贴上来有点乱

**Comment by luojiaquan7737** [comment]
`pi@raspberrypi:~/live $ screen -r 1190
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (mp3 (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0x189b4a0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[Parsed_ass_0 @ 0x18a7490] Bad timestamp
[Parsed_ass_0 @ 0x18a7490] Bad timestamp
[Parsed_ass_0 @ 0x18a7490] Bad timestamp
[Parsed_ass_0 @ 0x18a7490] Bad timestamp
[Parsed_ass_0 @ 0x18a7490] Added subtitle file: '/home/pi/live/default.ass' (6 styles, 4 events)
[swscaler @ 0x19a4360] deprecated pixel format used, make sure you did set range correctly
[h264_omx @ 0x18a2b20] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1152x720 [SAR 1:1 DAR 8:5], q=2-31, 200 kb/s, 3 fps, 1k tbn, 3 tbc
    Metadata:
      encoder         : Lavc57.89.100 h264_omx
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc57.89.100 aac
frame=    2 fps=0.0 q=-0.0 size=      37k`

完全没办法截全

**Comment by luojiaquan7737** [comment]
![default](https://user-images.githubusercontent.com/25074701/33384209-575e648a-d560-11e7-80c6-d3ea553236f5.PNG)

  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, image2, from '/home/pi/live/default_pic/ab.jpg':
  Duration: 00:00:00.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 1152x720 [SAR 72:72 DAR 8:5], 3 fps, 3 tbr, 3 tbn, 3 tbc
[mp3 @ 0x2e3c560] Estimating duration from bitrate, this may be inaccurate
Input #1, mp3, from '/home/pi/live/default_mp3/bx.mp3':
  Metadata:
    title           : Teddy
    album           : TVアニメ「神様のメモ帳」オリジナルサウンドトラック
    album_artist    : 岩崎琢
    artist          : 岩崎琢
  Duration: 00:04:10.44, start: 0.000000, bitrate: 146 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
    Stream #1:1: Video: png, rgb24(pc), 640x640, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Set the encoding preset (cf. x264 --fullhelp)) specified for output file #0 (rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (mp3 (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0x2e3a4a0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[Parsed_ass_0 @ 0x2e42de0] Bad timestamp
[Parsed_ass_0 @ 0x2e42de0] Bad timestamp
[Parsed_ass_0 @ 0x2e42de0] Bad timestamp
[Parsed_ass_0 @ 0x2e42de0] Bad timestamp
[Parsed_ass_0 @ 0x2e42de0] Added subtitle file: '/home/pi/live/default.ass' (6 styles, 4 events)
[swscaler @ 0x2f43360] deprecated pixel format used, make sure you did set range correctly
[h264_omx @ 0x2e41b20] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://dl.live-send.acg.tv/live-dl/?streamname=live_183468403_8504818&key=a844f496e1b17712a2cf3bce3c7a37c0':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1152x720 [SAR 1:1 DAR 8:5], q=2-31, 200 kb/s, 3 fps, 1k tbn, 3 tbc
    Metadata:
      encoder         : Lavc57.89.100 h264_omx
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc57.89.100 aac
frame=   28 fps=2.9 q=-0.0 size=     363kB time=00:00:08.73 bitrate= 341.0kbits/s speed=0.916x

**Comment by luojiaquan7737** [comment]
应该是这个吧

**Comment by chenxuuu** [comment]
把ass文件也贴上来看看

**Comment by luojiaquan7737** [comment]
default.ass截图
![sahdj](https://user-images.githubusercontent.com/25074701/33384855-1b6e0032-d562-11e7-88bf-355e272bcbf8.PNG)

**Comment by chenxuuu** [comment]
把99:00:00都改小一点试试
ffmpeg上面报错了看到没有，我没见过这种错误，也没插到资料

**Comment by luojiaquan7737** [comment]
好的，我试试，ffmpeg倒没发现报错

**Comment by luojiaquan7737** [comment]
将99：00：00全部改为59：00：00不能解决

**Comment by chenxuuu** [comment]
ffmpeg那么明显的绿色字体报错你给我说没发现报错？？？？

**Comment by luojiaquan7737** [comment]
不好意思，我以为报错他是红色字体，没想到是绿色，实在感到抱歉

**Comment by luojiaquan7737** [comment]
字幕报错如何解决或者等你发布一个修复版？

**Comment by chenxuuu** [comment]
我不知道原因，所以无法解决你的问题
另外这种问题应该只是个例
你可以检查一下你树莓派的系统时间

**Comment by zegzhi** [comment]
@luojiaquan7737 树莓派2同样问题，将字幕停留时间调整到8:00:00或以下才能正常。

**Comment by luojiaquan7737** [comment]
@zegzhi 不知这样能否艾特您，刚刚查看树莓派时间是没对。先尝试修正时间然后在尝试您的方法

**Comment by chenxuuu** [comment]
ok，确定是时间问题了吗？
是的话我改一下代码

**Comment by luojiaquan7737** [comment]
@chenxuuu 排除时间问题。按照 @zegzhi 方案将时间改为7可以显示

**Comment by chenxuuu** [comment]
@all-contributors please add @luojiaquan7737 for bug
