### ISSUE TITLE
[error]send dm error 'msg'

### ISSUE THREAD

**Issue by xhily** [chenxuuu/24h-raspberry-live-on-bilibili#60]
**描述bug**
简洁地写一下bug的内容
提示[error]send dm error
'msg'
**复现步骤**
按如下步骤可以复现bug：
1. 点歌 送礼 什么的提示这个

**本应出现的正常状态**
描述一下正常应该出现什么
cookies 和 csrf_token 都是按照教程 获取的 然后 运行就提示这个[error]send dm error
'msg'
**截屏或log记录**
尽量详细一些
![image](https://user-images.githubusercontent.com/15966687/60755942-8bbc7d80-a029-11e9-8375-9fc805d70231.png)

**环境信息**
 - 系统详细版本：[如 2019-06-07-raspbian-Buster]
 - 硬件信息： 树莓派3B+
 - 其他信息

**其他说明**
写出你想附加的其他信息

**Comment by chenxuuu** [comment]
实际弹幕发送出去了吗？

**Comment by xhily** [comment]
> 实际弹幕发送出去了吗？

没有

**Comment by chenxuuu** [comment]
![图片](https://user-images.githubusercontent.com/10357394/60764008-290fc400-a0b3-11e9-9e17-61b4202b8c2b.png)
![图片](https://user-images.githubusercontent.com/10357394/60764012-42b10b80-a0b3-11e9-92e6-0dedc8493843.png)

经测试，无任何问题

**Comment by xhily** [comment]
> ![图片](https://user-images.githubusercontent.com/10357394/60764008-290fc400-a0b3-11e9-9e17-61b4202b8c2b.png)
> ![图片](https://user-images.githubusercontent.com/10357394/60764012-42b10b80-a0b3-11e9-92e6-0dedc8493843.png)
> 
> 经测试，无任何问题

我再试试，麻烦了
