### ISSUE TITLE
弹幕发送失败

### ISSUE THREAD

**Issue by shinBZ** [chenxuuu/24h-raspberry-live-on-bilibili#61]
![DDD](https://user-images.githubusercontent.com/39182581/61944528-74d9cd00-afd0-11e9-8bf4-0499018866d1.JPG)

**Comment by chenxuuu** [comment]
测试无问题，请自行检查参数

![图片](https://user-images.githubusercontent.com/10357394/61960073-681c9f80-aff7-11e9-8677-f4a7e8f282c8.png)
![图片](https://user-images.githubusercontent.com/10357394/61960077-6b179000-aff7-11e9-8fde-95443d306171.png)

**Comment by shinBZ** [comment]
只会在发送温度参数上出错，别的无异常
尝试更改过文本发送长度，依旧异常。
