### ISSUE TITLE
发不出弹幕

### ISSUE THREAD

**Issue by emtry** [chenxuuu/24h-raspberry-live-on-bilibili#63]
[error]send dm error
'msg'

已设置两个参数

**Comment by huanghe2015** [comment]
我用第三方软件也发不出弹幕，估计接口改了。

**Comment by shilela** [comment]
post_dm.py文件中的send_dm函数中
"Referer":"http://live.bilibili.com/"+roomid改为"Referer":"https://live.bilibili.com/"+roomid
就可以解决问题
