### ISSUE TITLE
关于依赖包的安装

### ISSUE THREAD

**Issue by valext** [chenxuuu/24h-raspberry-live-on-bilibili#7]
我在安装依赖包时，出现libtool，texinfo这两个依赖出错
![image](https://user-images.githubusercontent.com/33391923/33381376-d3bc8bfe-d558-11e7-8d9c-3023516726fb.png)
而且直接使用解压编译也出现问题，请问该如何解决？

**Comment by chenxuuu** [comment]
依赖包安装属于linux常识问题，不在本项目解答范围内，请自行bing解决

**Comment by chenxuuu** [comment]
sudo apt-get update
