### ISSUE TITLE
运行python3 play.py和python3 bilibiliClient.py命令时报错

### ISSUE THREAD

**Issue by xuan-ming** [chenxuuu/24h-raspberry-live-on-bilibili#73]
**描述bug**
简洁地写一下bug的内容
root@aml:~/24h-raspberry-live-on-bilibili-master# python3 play.py               Traceback (most recent call last):
  File "play.py", line 6, in <module>
    from mutagen.mp3 import MP3
ModuleNotFoundError: No module named 'mutagen'
root@aml:~/24h-raspberry-live-on-bilibili-master# python3 bilibiliClient.py
Traceback (most recent call last):
  File "bilibiliClient.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**复现步骤**
按如下步骤可以复现bug：
1. 打开xxx
2. 发送xxx
3. xxxxx
4. 出现xxxx的bug

**本应出现的正常状态**
描述一下正常应该出现什么

**截屏或log记录**
尽量详细一些

**环境信息**
 - 系统详细版本：[No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
]
 - 硬件信息： [数码视讯q5]
 - 其他信息

**其他说明**
写出你想附加的其他信息

**Comment by chenxuuu** [comment]
```bash
sudo pip3 install aiohttp
```

你没执行

**Comment by xuan-ming** [comment]
执行sudo pip3 install aiohttp和sudo pip3 install mutagen时显示Command 'pip3' not found, but can be installed with:

apt install python3-pip
然后执行apt install python3-pip时显示正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
python3-pip 已经是最新版 (9.0.1-2.3~ubuntu1.18.04.1)。

**Comment by chenxuuu** [comment]
sudo python3 -m pip install aiohttp

**Comment by xuan-ming** [comment]
很抱歉再麻烦你，但是输入sudo python3 -m pip install aiohttp后有发生了错误，具体如下：
Collecting aiohttp
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://mirrors.aliyun.com/pypi/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
    100% |████████████████████████████████| 450kB 9.0MB/s
Collecting multidict<5.0,>=4.5 (from aiohttp)
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://mirrors.aliyun.com/pypi/packages/7f/8f/b3c8c5b062309e854ce5b726fc101195fbaa881d306ffa5c2ba19efa3af2/multidict-4.5.2.tar.gz (105kB)
    100% |████████████████████████████████| 112kB 2.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-twxepalm/multidict/

**Comment by chenxuuu** [comment]
https://cn.bing.com/search?q=No+module+named+%27setuptools%27

**Comment by xuan-ming** [comment]
你好，前面的问题都已经解决了，但是运行python3 play.py和python3 bilibiliClient.py之后直播间没有任何反应，下面附上图片。
![图片2](https://user-images.githubusercontent.com/56985761/67551325-34a6f980-f73b-11e9-99a4-ac18613ffe5a.png)

![图片1](https://user-images.githubusercontent.com/56985761/67551089-9e72d380-f73a-11e9-9eb7-9cafef12e8d0.png)

**Comment by chenxuuu** [comment]
你这算另一个问题了，新开一个issue

**Comment by xuan-ming** [comment]
好的
