### ISSUE TITLE
运行python3 play.py和screen python3 bilibiliClient.py之后直播间没有反应

### ISSUE THREAD

**Issue by xuan-ming** [chenxuuu/24h-raspberry-live-on-bilibili#74]
**描述bug**
简洁地写一下bug的内容
运行python3 play.py和screen python3 bilibiliClient.py之后直播间没有反应
![图片1](https://user-images.githubusercontent.com/56985761/67551580-da5a6880-f73b-11e9-883e-a9dde3d7fc6b.png)
![图片2](https://user-images.githubusercontent.com/56985761/67551585-de868600-f73b-11e9-86ef-568259564cfd.png)

**复现步骤**
按如下步骤可以复现bug：
1. 打开xxx
2. 发送xxx
3. xxxxx
4. 出现xxxx的bug

**本应出现的正常状态**
描述一下正常应该出现什么

**截屏或log记录**
尽量详细一些

**环境信息**
 - 系统详细版本：[如 2017-09-07-raspbian-stretch]
 - 硬件信息： [如 树莓派3B]
 - 其他信息

**其他说明**
写出你想附加的其他信息

**Comment by chenxuuu** [comment]
看截图没有看出有什么问题，都是正常的东西

**Comment by xuan-ming** [comment]
非常感谢，问题已经解决了，把模式改成vps就好了！ 1398695022 邮箱：1398695022@qq.com 签名由 网易邮箱大师 定制 在2019年10月25日 17:12，chenxuuu 写道： 看截图没有看出有什么问题，都是正常的东西 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
