### ISSUE TITLE
按照教材安装moviepy的时候遇到了困难

### ISSUE THREAD

**Issue by xuan-ming** [chenxuuu/24h-raspberry-live-on-bilibili#76]
**描述bug**
简洁地写一下bug的内容
运行pip3 install moviepy安装到最后显示以下内容
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9306_fsx/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jl4w9106-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9306_fsx/numpy/

**复现步骤**
按如下步骤可以复现bug：
1. 打开xxx
2. 发送xxx
3. xxxxx
4. 出现xxxx的bug

**本应出现的正常状态**
描述一下正常应该出现什么

**截屏或log记录**
尽量详细一些

**环境信息**
 - 系统详细版本：[如 2017-09-07-raspbian-stretch]
 - 硬件信息： [如 树莓派3B]
 - 其他信息

**其他说明**
写出你想附加的其他信息

**Comment by chenxuuu** [comment]
https://cn.bing.com/search?q=Command+%22%2Fusr%2Fbin%2Fpython3+-u+-c+%22import+setuptools%2C+tokenize%3B&pc=MOZI&form=MOZCON

**Comment by xuan-ming** [comment]
你好，按照上面的方法试了很久，还是和原来一样，缺少几个必要的依赖和库，但是都安装不上，安装过程报错和上面一样！ 1398695022 邮箱：1398695022@qq.com 签名由 网易邮箱大师 定制 在2019年10月28日 11:52，chenxuuu 写道： https://cn.bing.com/search?q=Command+%22%2Fusr%2Fbin%2Fpython3+-u+-c+%22import+setuptools%2C+tokenize%3B&pc=MOZI&form=MOZCON — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenxuuu** [comment]
你应该去pip或者moviepy项目下面提issue

**Comment by xuan-ming** [comment]
好的，很抱歉

**Comment by bmyjacks** [comment]
可以先安装zlib再用pip安装pillow最后装moviepy就能装上了

**Comment by xuan-ming** [comment]
已解决
