### ISSUE TITLE
海外vps是不是不能用

### ISSUE THREAD

**Issue by Linon419** [chenxuuu/24h-raspberry-live-on-bilibili#78]
海外vps，执行后没有任何反应，显示rtmp://js.live-send.acg.tv/live-js/?************************: Input/output error
rtmp没有错

**Comment by huanghe2015** [comment]
海外IP禁止几乎所有动作，包括弹幕和评论、动态。

**Comment by chenxuuu** [comment]
b站屏蔽了海外ip的直播操作
