### ISSUE TITLE
play.py 无法通过 clrt+c 键来停止

### ISSUE THREAD

**Issue by zegzhi** [chenxuuu/24h-raspberry-live-on-bilibili#8]
如题，clrt+c 后程序又循环启动，只能用kill来关了。
另：树莓派显存设置过低会导致硬解出错，但程序并不能正常关闭和上面一样又再次循环执行。

**Comment by chenxuuu** [comment]
用`screen -ls`显示所有screen
`screen -r id`可以查看改screen
`kill id`即可停止该screen内的所有进程
