### ISSUE TITLE
关于今早字幕文件更新问题

### ISSUE THREAD

**Issue by luojiaquan7737** [chenxuuu/24h-raspberry-live-on-bilibili#9]
经测试，之前不能显示字幕，将default.ass的四条99改为9即可，若是改动其他数据一样会出错。

**Comment by chenxuuu** [comment]
问题在下午就已修复
#6

**Comment by luojiaquan7737** [comment]
@chenxuuu 我晚上9点左右将项目下载到树莓派并启用，发现是不能显示字幕。

查看了ass_maker.py文件都不是99的了。我将此文件全部修改成99，

然后将默认字幕文件下面四条从12依次往下调发现9可以使用。四条是9，其他全为99都没有问题的。看起来可能有点乱。
并且昨晚提交的错误信息好像刚好指向这四条数据

**Comment by luojiaquan7737** [comment]
又自动崩了😂😂
